require("colinhermack")
require("colinhermack.lazy")

vim.cmd([[set number]])
vim.cmd([[filetype on]])
vim.cmd([[filetype indent on]])
vim.cmd([[syntax on]])
vim.cmd([[set cursorline]])
vim.cmd([[set shiftwidth=4]])
vim.cmd([[set tabstop=4]])
vim.cmd([[set expandtab]])
vim.cmd([[set scrolloff=10]])
vim.cmd([[set nowrap]])
vim.cmd([[set incsearch]])
vim.cmd([[set ignorecase]])
vim.cmd([[set showcmd]])
vim.cmd([[set showmatch]])
vim.cmd([[set wildignore=*.docx,*.jpg,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx]])
